defaults:
  - base_job_env

env:
  HP_DATA_DIR: $WORK/data/happypose
  HAPPYPOSE_DATA_DIR: $WORK/data/megapose
  BLENDER_INSTALL_DIR: $WORK/blender/blender-2.93.0-linux-x64
  BLENDERPROC_DIR: $WORK/projects/blenderproc
