defaults:
  - base_job_env

env:
  MEGAPOSE_DATA_DIR: /home/ylabbe/data/megapose-private
  BLENDER_INSTALL_DIR: $HOME/blenderproc/blender-2.93.88-linux-x64
  BLENDER_PROC_DIR: /home/ylabbe/projects/blenderproc