name: Tests with conda

on: [ push, pull_request ]

jobs:
  test:
    runs-on: ubuntu-latest
    defaults:
      run:
        shell: bash -el {0}
    strategy:
      matrix:
        python-version: ["3.9", "3.10"]
    steps:
      - uses: actions/checkout@v4
        with:
          submodules: 'recursive'
      - name: Install EGL mesa - required for Panda3D renderer
        run: |
          sudo apt-get update -y -qq
          sudo apt-get install -y -qq libegl1-mesa libegl1-mesa-dev

      - name: Setup conda
        uses: conda-incubator/setup-miniconda@v3
        with:
          activate-environment: happypose
          python-version: ${{ matrix.python-version }}
          miniforge-variant: Mambaforge
          miniforge-version: latest
          use-mamba: true

      - name: Get date for caching, reset cache every day
        id: get-date
        run: echo "::set-output name=today::$(/bin/date -u '+%Y%m%d')"
        shell: bash

      - name: Caching of the happypose installation and data
        uses: actions/cache@v4
        with:
          path: |
            ${{ env.CONDA }}/envs
            local_data
          key:
            conda-${{ runner.os }}--${{ runner.arch }}--${{steps.get-date.outputs.today }}-${{hashFiles('environment.yml') }}-${{env.CACHE_NUMBER }}
        env:
          # Increase this value to reset cache manually
          CACHE_NUMBER: 0
        id: cache

      - name: Update conda environment with happypose dependencies
        run: mamba env update -n happypose -f environment.yml
        if: steps.cache.outputs.cache-hit != 'true'

      - name: Install happypose
        run: pip install -e .

      - name: Download pre-trained models required for tests
        run: |
          mkdir -p local_data
          python -m happypose.toolbox.utils.download \
            --megapose_models \
            --examples \
              barbecue-sauce \
            --cosypose_models  \
              detector-bop-hope-pbr--15246 \
              coarse-bop-hope-pbr--225203 \
              refiner-bop-hope-pbr--955392

      - name: Run tests
        run: |
          python -m unittest
          pytest
