name: Tests with pip

on: [ push, pull_request ]

jobs:
  test:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        python-version: ["3.9", "3.10"]
    steps:
      - uses: actions/checkout@v4
        with:
          submodules: 'recursive'

      - name: Install EGL mesa - required for Panda3D renderer
        run: sudo apt-get update && sudo apt-get install -qqy libegl1-mesa libegl1-mesa-dev

      - name: Caching of the happypose installation and data
        uses: actions/cache@v4
        with:
          path: local_data
          key: data

      - uses: actions/setup-python@v5
        with:
          python-version: ${{ matrix.python-version }}

      - name: Update pip
        run: pip install -U pip

      - name: Install happypose
        run: pip install ".[cpu,pypi]" --extra-index-url https://download.pytorch.org/whl/cpu

      - name: Download pre-trained models required for tests
        run: |
          mkdir -p local_data
          python -m happypose.toolbox.utils.download \
            --megapose_models \
            --examples \
              barbecue-sauce \
            --cosypose_models  \
              detector-bop-hope-pbr--15246 \
              coarse-bop-hope-pbr--225203 \
              refiner-bop-hope-pbr--955392

      - name: Run tests
        run: |
          python -m unittest
          pytest
