name: Tests with poetry + Coverage

on: [ push, pull_request ]

jobs:
  test:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        python-version: ["3.9", "3.10"]
    steps:
      - uses: actions/checkout@v4
        with:
          submodules: 'recursive'

      - name: Install EGL mesa - required for Panda3D renderer
        run: sudo apt-get update && sudo apt-get install -qqy libegl1-mesa libegl1-mesa-dev

      - name: Setup poetry
        run: pipx install poetry

      - name: Caching of the happypose installation and data
        uses: actions/cache@v4
        with:
          path: local_data
          key: data

      - uses: actions/setup-python@v5
        with:
          python-version: ${{ matrix.python-version }}
          cache: poetry

      - name: Install happypose
        run: poetry install --with dev -E cpu -E evaluation -E pypi

      - name: Download pre-trained models required for tests
        run: |
          mkdir -p local_data
          poetry run python -m happypose.toolbox.utils.download \
            --megapose_models \
            --examples \
              crackers_example \
            --cosypose_models  \
              detector-bop-ycbv-pbr--970850 \
              coarse-bop-ycbv-pbr--724183 \
              refiner-bop-ycbv-pbr--604090

      - name: Run tests
        run: poetry run coverage run --source=happypose -m unittest

      - name: Process coverage
        run: poetry run coverage xml

      - uses: codecov/codecov-action@v3
        env:
          CODECOV_TOKEN: ${{ secrets.CODECOV_TOKEN }}
